name: Update Languages Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate card using API
        run: |
          curl -o public/languages-card.svg \
            "https://github-languages-card.vercel.app/api/top-languages?username=VIDAKHOSHPEY22&theme=pink"

      - name: Commit & Push if changed (with your identity)
        run: |
          # به جای github-actions[bot]، نام و ایمیل خودت را بگذار
          git config user.name "VIDAKHOSHPEY22"
          git config user.email "vviiddaa2@gmail.com"
          
          git add public/languages-card.svg
          
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          
          git commit -m "chore: auto-update languages card"
          git push